#include "test.h"
#include "utest.h"

SP_TEST_MAIN()

#include "sys/read.c"
#include "sys/pread.c"
#include "sys/write.c"
#include "sys/pwrite.c"
#include "sys/pipe.c"
#include "sys/transfer.c"
#include "sys/mkdir.c"
#include "sys/rmdir.c"
#include "sys/unlink.c"
#include "sys/rename.c"
#include "sys/link.c"
#include "sys/symlink.c"
#include "sys/stat.c"
#include "sys/root.c"
#include "sys/socket.c"
#include "sys/tty.c"
#include "sys/vtable.c"
