[package]
name = "sp"
version = "0.1.0"
include = ["."]

[[test]]
name = "amalgamation"
source = [
  "test/main.c",
  "test/test/*.c",
  "test/sys/sys.c", "test/sys/open.c", "test/sys/iter.c", "test/sys/futex.c",
  "test/sys/pipe.c", "test/sys/transfer.c", "test/sys/socket.c", "test/sys/listen.c",
  "test/sys/tty.c", "test/sys/tty_mode.c", "test/sys/vtable.c", "test/sys/event.c",
  "test/fs/iter/os.c", "test/fs/iter/iter.c",
  "test/mem/uninitialized.c",
  "test/atomic.c",
  "test/sync/*.c", "test/sync/os/*.c"
]

[[test]]
name = "meta"
source = ["test/main.c", "test/test/*.c", "test/test/wire/*.c"]

[[test]]
name = "sys"
source = [
  "test/main.c",
  "test/sys/sys.c", "test/sys/open.c", "test/sys/iter.c", "test/sys/futex.c",
  "test/sys/pipe.c", "test/sys/transfer.c", "test/sys/socket.c", "test/sys/listen.c",
  "test/sys/tty.c", "test/sys/tty_mode.c", "test/sys/vtable.c", "test/sys/event.c"
]

[[test]]
name = "atomic"
source = ["test/main.c", "test/atomic.c"]

[[test]]
name = "fs"
source = ["test/main.c", "test/fs/iter/iter.c", "test/fs/iter/os.c"]

[[test]]
name = "sync"
source = ["test/main.c", "test/sync/*.c", "test/sync/os/*.c"]

[[test]]
name = "mem"
source = ["test/main.c", "test/mem/uninitialized.c"]

[[bin]]
name = "zero_copy"
source = ["example/zero_copy.c"]
