<Project>
  <ItemGroup Condition="'$(SpSource)' != ''">
    <ClCompile Include="$(SpSource)" />
  </ItemGroup>
  <ItemGroup Condition="'$(SpHeaders)' != ''">
    <ClInclude Include="$(SpHeaders)" />
  </ItemGroup>
  <ItemGroup>
    <Natvis Include="$(MSBuildThisFileDirectory)sp.natvis" />
  </ItemGroup>
  <ItemGroup Condition="'$(SpProjectReferences)' != ''">
    <ProjectReference Include="$(SpProjectReferences)" />
  </ItemGroup>
  <Target Name="SpObjectNames" BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <ClCompile Condition="$([System.String]::Copy('%(RelativeDir)').StartsWith('..\'))">
        <ObjectFileName>$(IntDir)$([System.String]::Copy('%(RelativeDir)').Replace('..\', '').Replace('\', '_'))%(Filename).obj</ObjectFileName>
      </ClCompile>
    </ItemGroup>
  </Target>
  <Target Name="Run" DependsOnTargets="Build">
    <Exec Command="&quot;$(TargetPath)&quot;" />
  </Target>
</Project>
